Sidi.BearApp.UI.WebPortal/Controllers/AnimalsController.cs
using Sidi.CircusApp.Data.Entities;
using Sidi.CircusApp.Services.AnimalManagement;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sidi.CircusApp.UI.WebPortal.Controllers
{
    public class AnimalsController : Controller
    {

        // GET: Animals
        public ActionResult Index()
        {

            IEnumerable<Animal> result = null;
            try
            {
                var service = DependencyResolver.Current.GetService<IAnimalBusiness>();

                result = service.GetAnimals();
            }
            catch (Exception)
            {
                return View();
            }
            return View(result);
        }
        
        // Get: Animal by Id
        [HttpGet]
        public ActionResult Details(int id)
        {
            Animal result = null;
            try
            {
                var service = DependencyResolver.Current.GetService<IAnimalBusiness>();
                result = service.GetAnimalById(id);
            }
            catch (Exception)
            {
                return RedirectToAction("MyError", "Home");
            }
            return View(result);
        }

        public ActionResult Create()
        {
            return View();
        }
        // Create: Animals
        [HttpPost]
        public ActionResult Create(Animal model)
        {
            try
            {
                var service = DependencyResolver.Current.GetService<IAnimalBusiness>();
                service.CreateAnimal(model);
            }
            catch (Exception)
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Update(int id)
        {
            Animal result = null;
            try
            {
                var service = DependencyResolver.Current.GetService<IAnimalBusiness>();
                result = service.GetAnimalById(id);
            }
            catch (Exception)
            {
                return View();
            }
            return View(result);
        }

        [HttpPost]
        public ActionResult Update(Animal model)
        {
            try
            {
                var service = DependencyResolver.Current.GetService<IAnimalBusiness>();
                service.UpdateAnimal(model);
            }
            catch (Exception)
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }

        public JsonResult Delete(int id)
        {
            try
            {
                var service = DependencyResolver.Current.GetService<IAnimalBusiness>();
                service.DeleteAnimal(id);
            }
            catch (Exception)
            {
                return Json(
                        new
                        {
                            success = false
                        }
                    );
            }
            return Json(
                    new
                    {
                        success = true
                    }
                );
        }

    }
}

Sidi.BearApp.UI.WebPortal/Controllers/EventsController.cs
using Sidi.CircusApp.Services.EventManagement;
using Sidi.CircusApp.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sidi.CircusApp.UI.WebPortal.Controllers
{
    public class EventsController : Controller
    {
        // GET: Events
        public ActionResult Index()
        {
            IEnumerable<Event> result = null;
            try
            {
                var service = DependencyResolver.Current.GetService<IEventBusiness>();
                result = service.GetEvents();

            }
            catch (Exception)
            {
                return View();
            }
            return View(result);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Event model)
        {
            try
            {
                var service = DependencyResolver.Current.GetService<IEventBusiness>();
                service.CreateEvents(model);
            }
            catch (Exception)
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Update(int id)
        {
            Event result = null;
            try
            {
                var service = DependencyResolver.Current.GetService<IEventBusiness>();
                result = service.GetEventById(id);
            }
            catch (Exception)
            {
                return View();
            }
            return View(result);
        }

        [HttpPost]
        public ActionResult Update(Event model)
        {
            try
            {
                var service = DependencyResolver.Current.GetService<IEventBusiness>();
                service.UpdateEvent(model);
            }
            catch (Exception)
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }

        public JsonResult Delete(int id)
        {
            try
            {
                var service = DependencyResolver.Current.GetService<IEventBusiness>();
                service.DeleteEvent(id);
            }
            catch (Exception)
            {
                return Json(
                        new
                        {
                            success = false
                        }
                    );
            }
            return Json(
                    new
                    {
                        success = true
                    }
                );
        }
    }
}

Sidi.BearApp.UI.WebPortal/Controllers/HomeController.cs
using Sidi.CircusApp.Services.AnimalManagement;
using Sidi.CircusApp.Services.EventManagement;
using Sidi.CircusApp.Services.TrainerManagement;
using Sidi.CircusApp.UI.WebPortal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sidi.CircusApp.UI.WebPortal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var serviceB = DependencyResolver.Current.GetService<IAnimalBusiness>();
            var serviceT = DependencyResolver.Current.GetService<ITrainerBusiness>();
            var serviceE = DependencyResolver.Current.GetService<IEventBusiness>();

            var connected = serviceT.GetConnectedTrainer();
            HomeModel homeM = new HomeModel()
            {
                listB = serviceB.GetAnimals(),
                listT = serviceT.GetTrainers(),
                listE = serviceE.GetEvents()
            };

            return View(homeM);
        }
        public ActionResult MyError()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Sidi.BearApp.UI.WebPortal/Controllers/TrainersController.cs
using Sidi.CircusApp.Data.Entities;
using Sidi.CircusApp.Services.TrainerManagement;
using Sidi.CircusApp.Services.CircusManagement;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sidi.CircusApp.Services.AnimalManagement;

namespace Sidi.CircusApp.UI.WebPortal.Controllers
{
    public class TrainersController : Controller
    {
        // GET: Trainers
        public ActionResult Index()
        {
            IEnumerable<Trainer> result = null;
            try
            {
                var service = DependencyResolver.Current.GetService<ITrainerBusiness>();
                result = service.GetTrainers();
                    
            }
            catch (Exception)
            {
                return View();
            }
            return View(result);
        }

        public ActionResult Details(int id)
        {
            Trainer result = null;
            try
            {
                var service = DependencyResolver.Current.GetService<ITrainerBusiness>();
                result = service.GetTrainerById(id);
            }
            catch (Exception)
            {
                return View();
            }
            return View(result);
        }

        public JsonResult GetTrainerId()
        {
            Trainer result = null;
            try
            {
                var service = DependencyResolver.Current.GetService<ITrainerBusiness>();
                result = service.GetConnectedTrainer();
            }
            catch (Exception)
            {
                return Json(
                        new
                        {
                            success = false
                        }
                    );
            }
            return Json(
                    new
                    {
                        success = true,
                        data = new
                        {
                            name = result.Name,
                            id = result.TrainerId
                        }
                    },
                    JsonRequestBehavior.AllowGet
                );
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Trainer model)
        {
            try
            {
                var service = DependencyResolver.Current.GetService<ITrainerBusiness>();
                service.CreateTrainer(model);
            }
            catch (Exception)
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Update(int id)
        {
            Trainer result = null;
            try
            {
                var service = DependencyResolver.Current.GetService<ITrainerBusiness>();
                result = service.GetTrainerById(id);
            }
            catch (Exception)
            {
                return View();
            }
            return View(result);
        }

        [HttpPost]
        public ActionResult Update(Trainer model)
        {
            try
            {
                var service = DependencyResolver.Current.GetService<ITrainerBusiness>();
                service.UpdateTrainer(model);
            }
            catch (Exception)
            {
                return View(model);
            }
            return RedirectToAction("Details");
        }

        public ActionResult Delete(int id)
        {
            try
            {
                var service = DependencyResolver.Current.GetService<ITrainerBusiness>();
                service.DeleteTrainer(id);
            }
            catch (Exception)
            {
                return Json(
                        new
                        {
                            success = false
                        }
                    );
            }
            return Json(
                    new
                    {
                        success = true
                    }
                );
        }

        public ActionResult GetCircusData()
        {
            Circus result = null;
            try
            {
                var service = DependencyResolver.Current.GetService<ITrainerBusiness>();
                result = service.GetCircusData();
            }
            catch (Exception)
            {
                return View();
            }

            return View(result);
        }

        public ActionResult AffectTrainer(int id)
        {
            IEnumerable<Animal> result = null;
            try
            {
                var service = DependencyResolver.Current.GetService<ITrainerBusiness>();
                var serviceB = DependencyResolver.Current.GetService<IAnimalBusiness>();

                // On essaie de récupérer le trainer
                service.GetTrainerById(id);
                // Récupérer le trainer
                ViewBag.TrainerId = id;  

                // Récupérer les ours
                result = serviceB.GetAnimals();
            }
            catch (Exception)
            {
                return View("MyError","Home");
            }
            return View(result);
        }

        [HttpPost]
        public ActionResult AffectTrainer(int TrainerId, int BearId)
        {
            try
            {
                var service = DependencyResolver.Current.GetService<ITrainerBusiness>();
                service.AffectTrainerToAnimal(TrainerId, BearId);
            }
            catch (Exception)
            {
                return View();
            }
            return RedirectToAction("Index", "Bears");
        }

        public ActionResult DisaAffectTrainer(int id)
        {
            IEnumerable<Animal> result = null;
            try
            {
                var service = DependencyResolver.Current.GetService<ITrainerBusiness>();
                var serviceB = DependencyResolver.Current.GetService<IAnimalBusiness>();

                // On essaie de récupérer le trainer
                service.GetTrainerById(id);
                // Récupérer le trainer
                ViewBag.TrainerId = id;

                // Récupérer les ours
                result = serviceB.GetAnimals();
            }
            catch (Exception)
            {
                return View("MyError", "Home");
            }
            return View(result);
        }
        
        [HttpPost]
        public ActionResult DisaAffectTrainer(int TrainerId, int BearId)
        {
            try
            {
                var service = DependencyResolver.Current.GetService<ITrainerBusiness>();
                service.DisaffectTrainerToAnimal(TrainerId, BearId);
            }
            catch (Exception)
            {
                return View();
            }
            return RedirectToAction("Index", "Bears");
        }
    }
}

Sidi.BearApp.UI.WebPortal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Sidi.BearApp.UI.WebPortal/Views/Home/Index.cshtml
@model Sidi.CircusApp.UI.WebPortal.Models.HomeModel

@{
    ViewBag.Title = "Acceuil";
}
<div class="jumbotron">
    <div class="container body-content" style="text-align:center">
        <h1>CircusAPP Management</h1>
        <h2> Bonjour</h2>
        <p class="lead">L'application de gestion de personnel et d'Animaux de cirques</p>
    </div>
</div>

<div class="row">

    <div class="col-md-6">
        <span>Liste d'Animaux</span>
        <table class="table table-bordered table-hover">
            <tr>
                <th>
                    Nom
                </th>
                <th>
                    Race
                </th>
                <th>
                    Date de naissance
                </th>
                <th>
                    Sexe
                </th>
                <th>
                    Taille
                </th>
                <th>
                    Poids
                </th>
                <th>
                    Id du Père
                </th>
            </tr>
            @foreach (var item in Model.listB)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AnimalBreed)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Birthdate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gender)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Height)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Weight)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FatherId)
                    </td>
                </tr>
            }
        </table>
        @Html.ActionLink("Voir liste", "Index", "Animals")
        <hr />
    </div>

    @if (UserRoles.isAdmin())
    {
        <div class="col-md-6">
            <span>Liste de dresseurs</span>
            <table class="table table-bordered table-hover">
                <tr>
                    <th>
                        Noms du Dreseur
                    </th>
                    <th>
                        Admin
                    </th>
                </tr>
                @foreach (var item in Model.listT)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Admin)
                        </td>
                    </tr>
                }
            </table>
            @Html.ActionLink("Voir liste", "Index", "Trainers")
            <hr />
        </div>
    }

    <div class="col-md-6">
        <span>Liste d'historique de ticket de suivi</span>
        <table class="table table-bordered table-hover">
            <tr>
                <th>
                    AnimalId
                </th>
                <th>
                    TrainerId
                </th>
                <th>
                    Commentaires
                </th>
                <th>
                    Categories
                </th>
            </tr>
            @foreach (var item in Model.listE)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AnimalId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TrainerId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Comments)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category)
                    </td>
                </tr>
            }
        </table>
        @Html.ActionLink("Voir liste", "Index", "Events")
    </div>

</div>

Sidi.BearApp.UI.WebPortal/Views/Home/MyError.cshtml
@{
    ViewBag.Title = "MyError";
}

<h2>MyError</h2>